export IMAGE_TAG_REACT="${ECR_REGISTRY}/${APP_REPO_NAME}:react-b${BUILD_NUMBER}"
export IMAGE_TAG_NODE="${ECR_REGISTRY}/${APP_REPO_NAME}:node-b${BUILD_NUMBER}"
export IMAGE_TAG_POSTGRES="${ECR_REGISTRY}/${APP_REPO_NAME}:postgres-b${BUILD_NUMBER}"